version: '3.9'

services:
  db:
    image: postgres:13
    container_name: linendev_postgres
    restart: always
    ports:
      - '${DB_PORT}:${DB_PORT}'
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PORT=${DB_PORT}
      - PGDATA=/var/lib/postgresql/data/pgdata
      - APP_DB=linendev,linentest
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
      - ./postgres/initdb:/docker-entrypoint-initdb.d
    network_mode: bridge

  web:
    container_name: web
    profiles: ['apps']
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        - MODULE=@linen/web
    restart: always
    volumes:
      - .:/usr/src/app
      - ./usr/src/app/node_modules
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:postgres@host.docker.internal:5432/postgres
    depends_on:
      - db
    network_mode: bridge
    command: sh -c "cd apps/web && npm run start"

  api:
    container_name: api
    profiles: ['apps']
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        - MODULE=@linen/api
    restart: always
    volumes:
      - .:/usr/src/app
      - ./usr/src/app/node_modules
    ports:
      - 3001:3001
    env_file:
      - .env
    environment:
      - PORT=3001
      - DATABASE_URL=postgresql://postgres:postgres@host.docker.internal:5432/postgres
    depends_on:
      - db
    network_mode: bridge
    command: sh -c "node apps/api/dist/index.js"

volumes:
  pgdata:
